### ISSUE TITLE
Remove textwatcher listener

### ISSUE THREAD

**Issue by brezinajn** [pawegio/KAndroid#19]
Is there any way to remove listener added by textWatcher extension function?
Thanks :)

**Comment by pawegio** [comment]
Hi @brezinajn, yes it's possible 🙂
You can access `TextWatcher` reference inside lambda and assign it to variable:

```
var textWatcher: TextWatcher? = null
textView.textWatcher {
    textWatcher = this
}
textView.removeTextChangedListener(textWatcher)
```

**Comment by brezinajn** [comment]
Uhm, missed that one :)
Thanks :)
