### ISSUE TITLE
Add lambda log methods

### ISSUE THREAD

**Issue by pawegio** [pawegio/KAndroid#2]
e.g.

```
d { “Some potentially expensive message here" }
```

thanks @asarazan for suggestion

**Comment by asarazan** [comment]
:+1:

**Comment by asarazan** [comment]
Fyi maybe made moot by anko? Unsure: https://github.com/JetBrains/anko/blob/master/doc/ADVANCED.md#logging

**Comment by pawegio** [comment]
Ok, I'll borrow it probably from anko
