### ISSUE TITLE
Vals for check external storage readable/writable

### ISSUE THREAD

**Issue by illuzor** [pawegio/KAndroid#26]
I would like to propose two useful vals:
``` kotlin
val isExternalStorageWritable
    get() = Environment.MEDIA_MOUNTED == Environment.getExternalStorageState()

val isExternalStorageReadable
    get() = Environment.MEDIA_MOUNTED_READ_ONLY == Environment.getExternalStorageState() || externalStorageWritable
```
But I don`t know where to add them. I mean which file. Maybe create a new one?

**Comment by pawegio** [comment]
* Firstly, I would prefer extensions on `Environment` class instead of declaring top-level vals (visible everywhere). 
* Then I would add `inline` modifier to both properties, create `KEnvironment.kt` file and put vals inside.
