### ISSUE TITLE
getSystemService(...) getters should be nullable

### ISSUE THREAD

**Issue by passsy** [pawegio/KAndroid#3]
the extension functions in [`KContext`](https://github.com/pawegio/KAndroid/blob/master/kandroid/src/main/java/com/pawegio/kandroid/KContext.kt#L131) should return a Nullable type of the service. It is very common that those services do not exist.

i.e. this should be changed for the JobScheduler

``` diff
+ val Context.jobScheduler: JobScheduler?
- val Context.jobScheduler: JobScheduler
    get() = getSystemService(Context.JOB_SCHEDULER_SERVICE) as JobScheduler
```

same for all other `getSystemService(...)` functions

**Comment by pawegio** [comment]
Thanks for investigation. Fixed in 0.6.8 version.
