### ISSUE TITLE
Change request: making runOnUiThread method conststent with the Android API method

### ISSUE THREAD

**Issue by jakubvimn** [pawegio/KAndroid#30]
The API method
https://developer.android.com/reference/android/app/Activity.html#runOnUiThread(java.lang.Runnable)
doesn't use Handler when the calling thread is UI, whereas
the method runOnUiThread from here 
https://github.com/pawegio/KAndroid/blob/master/kandroid/src/main/kotlin/com/pawegio/kandroid/KThread.kt
always uses Handler.

I think that the inconsistency between these 2 methods may be confusing.

**Comment by pawegio** [comment]
Good catch, I'll fix it shortly.
