### ISSUE TITLE
Is there any way to suppress the warning in callsite when using fromApi/toApi?

### ISSUE THREAD

**Issue by Edward608** [pawegio/KAndroid#43]
It is quite annoying to see those unnecessary warnings in the call site of these two inline functions, since the api level check is already done.

**Comment by pawegio** [comment]
For now the only/best way is to surround function with `@TargetApi(..)` annotation:

```kotlin
@TargetApi(26)
fun foo() {
    fromApi(26) { /* ... */ }
}
```

whereas in the call site...
I would disable this inpection in IDE:

![zrzut ekranu 2017-08-30 o 23 23 29](https://user-images.githubusercontent.com/876573/29895704-67ab9e52-8dda-11e7-9f22-75b303253059.png)

Hope it will be fixed after better kotlin support.
