### ISSUE TITLE
Problem with Gradle 4.9

### ISSUE THREAD

**Issue by carmas123** [pawegio/KAndroid#55]
Hi, after upgrade to Gradle 4.9 this library does not work again...

**Comment by illuzor** [comment]
"does not work" is not a correct description of a problem. Any errors?
I will update the lib for as3.2 and gradle 4.9, but better to know what`s wrong.

**Comment by carmas123** [comment]
The problem isn't with Gradle 4.9, but it's with com.android.tools.build:gradle:3.3.0-alpha06

**Comment by carmas123** [comment]
With alpha04 no problem...with alpha05 I got an hint...with 06 I got an error:
Unresolved reference. None of the following candidates is applicable because of receiver type mismatch
