### ISSUE TITLE
Unable to resolve dependency | Android Studio 4.0 | Gradle 4.0 6.1.1

### ISSUE THREAD

**Issue by Andrey-Morenkov** [pawegio/KAndroid#62]
Updated Android Studio to 4.0 with also updated gradle and now it doesn't building:

Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.pawegio.kandroid:kandroid:0.8.8.

{
  "errors" : [ {
    "status" : 409,
    "message" : "The repository 'oss-snapshot-local' rejected the resolution of an artifact 'oss-snapshot-local:com/pawegio/kandroid/kandroid/0.8.8/kandroid-0.8.8.pom' due to conflict in the snapshot release handling policy."
  } ]
}

**Comment by janzzend** [comment]
How are you able to resolve this?
