### ISSUE TITLE
migrate from jcenter to other host, like mavenCentral

### ISSUE THREAD

**Issue by nashihu** [pawegio/KAndroid#64]
hello, thanks for the library

[JCenter is at end of life](https://stackoverflow.com/questions/66400264/jcenter-is-at-end-of-life-android-lint-warning-what-is-the-replacement)

[Developers who publish artifacts on JCenter should migrate their packages to a new host, such as Maven Central.](https://developer.android.com/studio/build/jcenter-migration)

any thought, when and where you will migrate your libraries?

Thank you..

**Comment by nashihu** [comment]
i just realized from [here](https://github.com/pawegio/KAndroid/issues/63#issuecomment-647369364) that this lib also uploaded in [jitpack](https://jitpack.io/#pawegio/kandroid), but still there's an issue regarding the latest version of 0.8.7

if one use version 0.8.7 in gradle, we'll see there's no class from the downloaded library, and also the imported codes will be failed to resolve, like this pict below
![image](https://user-images.githubusercontent.com/35857544/119445250-b5363d80-bd56-11eb-98af-7e32fbc37bbc.png)

but when we use 0.8.4 in gradle, we can see the codes and imported codes will success to resolve, like this pict below
![image](https://user-images.githubusercontent.com/35857544/119445157-96d04200-bd56-11eb-804d-f1e13b0cd919.png)

i think it's about configuration from the maven or bintray like mentioned at #63 to solve it

**Comment by nashihu** [comment]
adding `@aar` solve the problem

the [jitpack](https://jitpack.io/#pawegio/kandroid/v0.8.7) documentation should be edited to not making people made mistakes, here the screenshot:

![image](https://user-images.githubusercontent.com/35857544/119446759-24149600-bd59-11eb-92be-6acc85dbb9ee.png)

or maybe the README.md itself should be edited

it should be 
```
dependencies {
     implementation 'com.github.pawegio:KAndroid:0.8.7@aar'
}
```

**Comment by pawegio** [comment]
Thank you @nashihu for contribution! JCenter went to into read-only state so old artifacts should be available, but JitPack is now the preferred way.
